version: "3.3"
services:
  landing-service:
    build: ./landing
    hostname: landing-service
    ports:
      - "5050:5050"
    networks:
      - my-network
    depends_on:
      - usd-service
      - eur-service
      - gbp-service
      - jpy-service
      - cad-service
      - aud-service
      - chf-service

  usd-service:
    build: ./usd
    hostname: usd-service
    ports:
      - "5001:5050"
    networks:
      - my-network

  eur-service:
    build: ./eur
    ports:
      - "5002:5050"
    networks:
      - my-network

  gbp-service:
    build: ./gbp
    ports:
      - "5003:5050"
    networks:
      - my-network

  jpy-service:
    build: ./jpy
    ports:
      - "5011:5050"
    networks:
      - my-network

  cad-service:
    build: ./cad
    ports:
      - "5012:5050"
    networks:
      - my-network

  aud-service:
    build: ./aud
    ports:
      - "5013:5050"
    networks:
      - my-network

  chf-service:
    build: ./chf
    ports:
      - "5014:5050"
    networks:
      - my-network

networks:
  my-network:
